import { Link } from 'react-router-dom';

export function LandingPage({ nav }: { nav: React.ReactNode }) {
  return <main className="shell">{nav}
    <section className="hero landing-hero"><p className="eyebrow">AGENT-BASED SOCIOLINGUISTICS</p><h1>See how social structure shapes accent change.</h1><p className="lede">Mosaic lets you test how local influence, network structure, and random drift can make accents converge, cluster, or persist.</p><div className="actions"><Link className="btn btn-primary" to="/simulate">Run a simulation →</Link><Link className="btn btn-secondary" to="/guide">Learn how it works</Link></div></section>
    <section className="run-glance" aria-label="What a completed simulation produces"><div><p className="eyebrow">A RUN AT A GLANCE</p><h2>From a social question to inspectable evidence.</h2><p>A completed run gives you a convergence outcome, a changing diversity trajectory, a social network, and a projection of accent similarity.</p></div><div className="glance-metrics"><div><span>Outcome</span><strong>Converged or persistent</strong></div><div><span>Evidence</span><strong>Network + accent space</strong></div><div><span>Reproducible</span><strong>Configuration and seed</strong></div></div></section>
    <section className="section"><h2>Questions you can explore</h2><div className="grid"><article className="card"><h3>Does topology matter?</h3><p>Compare random, small-world, scale-free, and two-community networks.</p></article><article className="card"><h3>Do hubs shape the outcome?</h3><p>Increase prestige influence to test whether central speakers pull others toward them.</p></article><article className="card"><h3>When do communities merge?</h3><p>Change bridge density to see when separated groups begin to share an accent pattern.</p></article></div></section>
    <section className="section credibility"><p className="eyebrow">RESEARCH SURFACES</p><h2>Designed as a transparent research demonstration.</h2><p className="lede">Browse pre-computed experiments, compare reproducible runs, or review the graph-learning benchmark and its limitations.</p><div className="actions"><Link className="btn btn-secondary" to="/experiments">View experiments</Link><Link className="btn btn-secondary" to="/analysis">Read ML analysis</Link></div></section>
  </main>;
}
